services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/algo_sangaku
      - public-data:/algo_sangaku_back/public
      - tmp-data:/algo_sangaku_back/tmp
      - log-data:/algo_sangaku_back/log
    environment:
      TZ: Asia/Tokyo
    networks:
      - algo_sangaku_back-network
  nginx:
    build:
      context: ./nginx_docker_prod
    volumes:
      - public-data:/algo_sangaku_back/public
      - tmp-data:/algo_sangaku_back/tmp
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - algo_sangaku_back-network
volumes:
  public-data:

  tmp-data:
  log-data:
  db-data:

networks:
  algo_sangaku_back-network:
    external: true
