---
openapi: 3.2.0
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/admin/sangakus":
    get:
      summary: index
      tags:
      - Api::V1::Admin::Sangaku
      responses:
        '200':
          description: returns 200 with sangakus list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
                            difficulty:
                              type: string
                            created_at:
                              type: string
                            user_name:
                              type: string
                            shrine_name:
                              type: 'null'
                            description:
                              type: string
                            source:
                              type: string
                          required:
                          - title
                          - difficulty
                          - created_at
                          - user_name
                          - shrine_name
                      required:
                      - id
                      - type
                      - attributes
                required:
                - data
              example:
                data:
                - id: '169'
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    source: puts 'Hello world'
                    difficulty: easy
                    created_at: '2026-09-01T00:01:40.910+09:00'
                    user_name: test nickname
                    shrine_name:
        '401':
          description: returns 401
          content:
            text/plain:
              schema:
                type: string
              example: 'HTTP Token: Access denied.

                '
        '403':
          description: returns 403
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items: {}
                required:
                - message
                - errors
              example:
                message: Forbidden
                errors: []
  "/api/v1/admin/sangakus/{id}":
    delete:
      summary: destroy
      tags:
      - Api::V1::Admin::Sangaku
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 186
      responses:
        '200':
          description: returns 200 and deletes the sangaku
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          difficulty:
                            type: string
                          created_at:
                            type: string
                          user_name:
                            type: string
                          shrine_name:
                            type: 'null'
                          description:
                            type: string
                          source:
                            type: string
                        required:
                        - title
                        - difficulty
                        - created_at
                        - user_name
                        - shrine_name
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '182'
                  type: sangaku
                  attributes:
                    title: test_title
                    difficulty: easy
                    created_at: '2026-09-01T00:01:41.200+09:00'
                    user_name: test nickname
                    shrine_name:
                    description: test_description
                    source: puts 'Hello world'
        '401':
          description: returns 401
          content:
            text/plain:
              schema:
                type: string
              example: 'HTTP Token: Access denied.

                '
        '403':
          description: returns 403
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items: {}
                required:
                - message
                - errors
              example:
                message: Forbidden
                errors: []
    get:
      summary: show
      tags:
      - Api::V1::Admin::Sangaku
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 175
      responses:
        '200':
          description: returns 200 with sangaku attributes
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          difficulty:
                            type: string
                          created_at:
                            type: string
                          user_name:
                            type: string
                          shrine_name:
                            type: 'null'
                          description:
                            type: string
                          source:
                            type: string
                        required:
                        - title
                        - difficulty
                        - created_at
                        - user_name
                        - shrine_name
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '172'
                  type: sangaku
                  attributes:
                    title: test_title
                    difficulty: easy
                    created_at: '2026-09-01T00:01:40.999+09:00'
                    user_name: test nickname
                    shrine_name:
                    description: test_description
                    source: puts 'Hello world'
        '401':
          description: returns 401
          content:
            text/plain:
              schema:
                type: string
              example: 'HTTP Token: Access denied.

                '
        '403':
          description: returns 403
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items: {}
                required:
                - message
                - errors
              example:
                message: Forbidden
                errors: []
    patch:
      summary: update
      tags:
      - Api::V1::Admin::Sangaku
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 181
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sangaku:
                  type: object
                  properties:
                    title:
                      type: string
                    difficulty:
                      type: string
                    description:
                      type: string
                    source:
                      type: string
                  required:
                  - title
                  - difficulty
                  - description
                  - source
              required:
              - sangaku
            example:
              sangaku:
                title: 更新タイトル
                difficulty: normal
                description: 更新説明文
                source: puts 'updated'
      responses:
        '200':
          description: returns 200 and updates the sangaku
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          description:
                            type: string
                          source:
                            type: string
                          difficulty:
                            type: string
                          created_at:
                            type: string
                          user_name:
                            type: string
                          shrine_name:
                            type: 'null'
                        required:
                        - title
                        - description
                        - source
                        - difficulty
                        - created_at
                        - user_name
                        - shrine_name
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '176'
                  type: sangaku
                  attributes:
                    title: 更新タイトル
                    description: 更新説明文
                    source: puts 'updated'
                    difficulty: normal
                    created_at: '2026-09-01T00:01:41.047+09:00'
                    user_name: test nickname
                    shrine_name:
        '401':
          description: returns 401
          content:
            text/plain:
              schema:
                type: string
              example: 'HTTP Token: Access denied.

                '
        '403':
          description: returns 403
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items: {}
                required:
                - message
                - errors
              example:
                message: Forbidden
                errors: []
