---
openapi: 3.2.0
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/admin/users":
    get:
      summary: index
      tags:
      - Api::V1::Admin::User
      responses:
        '200':
          description: returns users in descending order when sort=desc
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            email:
                              type: string
                            nickname:
                              type: string
                            role:
                              type: string
                            created_at:
                              type: string
                            sangaku_count:
                              type: integer
                            answer_count:
                              type: integer
                          required:
                          - name
                          - email
                          - nickname
                          - role
                          - created_at
                          - sangaku_count
                          - answer_count
                      required:
                      - id
                      - type
                      - attributes
                required:
                - data
              example:
                data:
                - id: '32895'
                  type: user
                  attributes:
                    name: test user
                    email: user_154@example.com
                    nickname: test nickname
                    role: general
                    created_at: '2026-09-14T17:28:54.093+09:00'
                    sangaku_count: 0
                    answer_count: 0
                - id: '32894'
                  type: user
                  attributes:
                    name: test user
                    email: user_153@example.com
                    nickname: test nickname
                    role: admin
                    created_at: '2026-09-14T17:28:54.091+09:00'
                    sangaku_count: 0
                    answer_count: 0
                - id: '32897'
                  type: user
                  attributes:
                    name: test user
                    email: user_156@example.com
                    nickname: test nickname
                    role: general
                    created_at: '2026-09-13T17:28:54.096+09:00'
                    sangaku_count: 0
                    answer_count: 0
                - id: '32896'
                  type: user
                  attributes:
                    name: test user
                    email: user_155@example.com
                    nickname: test nickname
                    role: general
                    created_at: '2026-09-12T17:28:54.094+09:00'
                    sangaku_count: 0
                    answer_count: 0
        '401':
          description: returns 401
          content:
            text/plain:
              schema:
                type: string
              example: 'HTTP Token: Access denied.

                '
        '403':
          description: returns 403
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items: {}
                required:
                - message
                - errors
              example:
                message: Forbidden
                errors: []
      parameters:
      - name: query
        in: query
        required: false
        schema:
          type: string
        example: search_target@
      - name: sort
        in: query
        required: false
        schema:
          type: string
        example: desc
  "/api/v1/admin/users/{id}":
    get:
      summary: show
      tags:
      - Api::V1::Admin::User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 32916
      responses:
        '200':
          description: returns 200 with user attributes
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
                          email:
                            type: string
                          nickname:
                            type: string
                          role:
                            type: string
                          created_at:
                            type: string
                          sangaku_count:
                            type: integer
                          answer_count:
                            type: integer
                        required:
                        - name
                        - email
                        - nickname
                        - role
                        - created_at
                        - sangaku_count
                        - answer_count
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '32907'
                  type: user
                  attributes:
                    name: test user
                    email: user_166@example.com
                    nickname: test nickname
                    role: general
                    created_at: '2026-09-14T17:28:54.145+09:00'
                    sangaku_count: 0
                    answer_count: 0
        '401':
          description: returns 401
          content:
            text/plain:
              schema:
                type: string
              example: 'HTTP Token: Access denied.

                '
        '403':
          description: returns 403
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items: {}
                required:
                - message
                - errors
              example:
                message: Forbidden
                errors: []
    patch:
      summary: update
      tags:
      - Api::V1::Admin::User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 32937
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    role:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
                  required:
                  - role
              required:
              - user
            example:
              user:
                role: admin
                name: hacked
                email: hacked@example.com
      responses:
        '200':
          description: does not change name or email even if passed
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
                          email:
                            type: string
                          nickname:
                            type: string
                          role:
                            type: string
                          created_at:
                            type: string
                          sangaku_count:
                            type: integer
                          answer_count:
                            type: integer
                        required:
                        - name
                        - email
                        - nickname
                        - role
                        - created_at
                        - sangaku_count
                        - answer_count
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '32925'
                  type: user
                  attributes:
                    name: test user
                    email: user_184@example.com
                    nickname: test nickname
                    role: admin
                    created_at: '2026-09-14T17:28:54.242+09:00'
                    sangaku_count: 0
                    answer_count: 0
        '401':
          description: returns 401
          content:
            text/plain:
              schema:
                type: string
              example: 'HTTP Token: Access denied.

                '
        '403':
          description: returns 403
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items: {}
                required:
                - message
                - errors
              example:
                message: Forbidden
                errors: []
