---
openapi: 3.0.3
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/authenticate":
    delete:
      summary: destroy
      tags:
      - Api::V1::Authenticate
      responses:
        '200':
          description: return success message with json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
              example:
                message: signout successful
    post:
      summary: create
      tags:
      - Api::V1::Authenticate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
              - token
            example:
              token: dummy_idtoken
      responses:
        '200':
          description: user does not create
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          provider:
                            type: string
                          uid:
                            type: string
                          name:
                            type: string
                          email:
                            type: string
                          nickname:
                            type: string
                        required:
                        - provider
                        - uid
                        - name
                        - email
                        - nickname
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '53'
                  type: user
                  attributes:
                    provider: google
                    uid: 5dbecd5d-7faa-485d-afd4-871960a06e6c
                    name: test user
                    email: user_2@example.com
                    nickname: test nickname
