---
openapi: 3.0.3
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/shrines/{shrine_id}/sangakus":
    get:
      summary: index
      tags:
      - Api::V1::ShrinesSangaku
      parameters:
      - name: difficulty
        in: query
        required: false
        schema:
          type: string
        example: nomal
      - name: shrine_id
        in: path
        required: true
        schema:
          type: integer
        example: 545
      - name: title
        in: query
        required: false
        schema:
          type: string
        example: test_title
      responses:
        '200':
          description: return sangakus in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
                            description:
                              type: string
                            source:
                              type: string
                            difficulty:
                              type: string
                            inputs:
                              type: array
                              items: {}
                            author_name:
                              type: string
                          required:
                          - title
                          - description
                          - source
                          - difficulty
                          - inputs
                          - author_name
                        relationships:
                          type: object
                          properties:
                            user:
                              type: object
                              properties:
                                data:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                              required:
                              - data
                            shrine:
                              type: object
                              properties:
                                data:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                              required:
                              - data
                          required:
                          - user
                          - shrine
                      required:
                      - id
                      - type
                      - attributes
                      - relationships
                required:
                - data
              example:
                data:
                - id: '838'
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    source: puts 'Hello world'
                    difficulty: nomal
                    inputs: []
                    author_name: test nickname
                  relationships:
                    user:
                      data:
                        id: '1336'
                        type: user
                    shrine:
                      data:
                        id: '545'
                        type: shrine
