---
openapi: 3.0.3
info:
  title: myapp
  version: 1.0.0
servers: []
paths:
  "/api/v1/sangakus":
    post:
      summary: create
      tags:
      - Api::V1::Sangaku
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sangaku:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    source:
                      type: string
                    difficulty:
                      type: string
                  required:
                  - title
                  - description
                  - source
                  - difficulty
                fixed_inputs:
                  type: array
                  items:
                    type: string
                    properties:
                      content:
                        type: string
                    required:
                    - content
              required:
              - sangaku
              - fixed_inputs
            example:
              sangaku:
                title: test_title
                description: test_description
                source: put 'Hello world'
                difficulty: easy
              fixed_inputs:
              - test_input_3
      responses:
        '200':
          description: return sangaku in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          description:
                            type: string
                          source:
                            type: string
                          difficulty:
                            type: string
                          inputs:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                content:
                                  type: string
                              required:
                              - id
                              - content
                        required:
                        - title
                        - description
                        - source
                        - difficulty
                        - inputs
                      relationships:
                        type: object
                        properties:
                          user:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                - id
                                - type
                            required:
                            - data
                        required:
                        - user
                    required:
                    - id
                    - type
                    - attributes
                    - relationships
                required:
                - data
              example:
                data:
                  id: '70'
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    source: put 'Hello world'
                    difficulty: easy
                    inputs:
                    - id: 15
                      content: test_input_3
                  relationships:
                    user:
                      data:
                        id: '70'
                        type: user
  "/api/v1/shrines":
    get:
      summary: index
      tags:
      - Api::V1::Shrine
      parameters:
      - name: highLat
        in: query
        required: false
        schema:
          type: string
        example: '35.5'
      - name: highLng
        in: query
        required: false
        schema:
          type: string
        example: '135.2'
      - name: lat
        in: query
        required: false
        schema:
          type: string
        example: '35.4'
      - name: lng
        in: query
        required: false
        schema:
          type: string
        example: '135.2'
      - name: lowLat
        in: query
        required: false
        schema:
          type: string
        example: '35.4'
      - name: lowLng
        in: query
        required: false
        schema:
          type: string
        example: '135.1'
      - name: searchType
        in: query
        required: false
        schema:
          type: string
        example: List
      responses:
        '200':
          description: shrines does not create
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            address:
                              type: string
                            latitude:
                              type: number
                              format: float
                            longitude:
                              type: number
                              format: float
                            place_id:
                              type: string
                          required:
                          - name
                          - address
                          - latitude
                          - longitude
                          - place_id
                      required:
                      - id
                      - type
                      - attributes
                required:
                - data
              example:
                data:
                - id: '48'
                  type: shrine
                  attributes:
                    name: test_shrine
                    address: test_address
                    latitude: 35.70204829610801
                    longitude: 139.76789333814216
                    place_id: test_place_id_14
        '400':
          description: return 400
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      type: string
                required:
                - message
                - errors
              example:
                message: Bad Request
                errors:
                - invalid params
  "/api/v1/users":
    post:
      summary: create
      tags:
      - Api::V1::User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
              - token
            example:
              token: dummy_idtoken
      responses:
        '200':
          description: user does not create
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          provider:
                            type: string
                          uid:
                            type: string
                          name:
                            type: string
                          email:
                            type: string
                          nickname:
                            type: string
                        required:
                        - provider
                        - uid
                        - name
                        - email
                        - nickname
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '72'
                  type: user
                  attributes:
                    provider: google
                    uid: e1af92cc-cfa6-4c5b-b161-49cb074351af
                    name: test user
                    email: user_27@example.com
                    nickname: test nickname
  "/up":
    get:
      summary: show
      tags:
      - Rails::Health
      responses:
        '200':
          description: works! (now write some real specs)
          content:
            text/html:
              schema:
                type: string
              example: '<!DOCTYPE html><html><body style="background-color: green"></body></html>'
