---
openapi: 3.2.0
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/user/answers/{id}":
    get:
      summary: show
      tags:
      - Api::V1::User::Answer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 43
      responses:
        '200':
          description: return answer in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          source:
                            type: string
                          status:
                            type: string
                        required:
                        - source
                        - status
                      relationships:
                        type: object
                        properties:
                          user_sangaku_save:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                - id
                                - type
                            required:
                            - data
                          answer_results:
                            type: object
                            properties:
                              data:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                            required:
                            - data
                        required:
                        - user_sangaku_save
                        - answer_results
                    required:
                    - id
                    - type
                    - attributes
                    - relationships
                required:
                - data
              example:
                data:
                  id: '43'
                  type: answer
                  attributes:
                    source: puts 'Hello world'
                    status: pending
                  relationships:
                    user_sangaku_save:
                      data:
                        id: '77'
                        type: user_sangaku_save
                    answer_results:
                      data:
                      - id: '43'
                        type: answer_result
