---
openapi: 3.0.3
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/user/profile":
    get:
      summary: show
      tags:
      - Api::V1::User::Profile
      responses:
        '200':
          description: マイプロフィールを返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          email:
                            type: string
                          nickname:
                            type: string
                          show_answer_count:
                            type: boolean
                          created_at:
                            type: string
                          sangaku_count:
                            type: integer
                          dedicated_sangaku_count:
                            type: integer
                          saved_sangaku_count:
                            type: integer
                          answer_count:
                            type: integer
                        required:
                        - email
                        - nickname
                        - show_answer_count
                        - created_at
                        - sangaku_count
                        - dedicated_sangaku_count
                        - saved_sangaku_count
                        - answer_count
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '82'
                  type: my_profile
                  attributes:
                    email: user_1@example.com
                    nickname: test nickname
                    show_answer_count: false
                    created_at: '2026-04-17T14:59:30.299+09:00'
                    sangaku_count: 2
                    dedicated_sangaku_count: 1
                    saved_sangaku_count: 0
                    answer_count: 0
    patch:
      summary: update
      tags:
      - Api::V1::User::Profile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    nickname:
                      type: string
                  required:
                  - nickname
              required:
              - user
            example:
              user:
                nickname: changed_name
      responses:
        '200':
          description: return user in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          provider:
                            type: string
                          uid:
                            type: string
                          name:
                            type: string
                          email:
                            type: string
                          nickname:
                            type: string
                        required:
                        - provider
                        - uid
                        - name
                        - email
                        - nickname
                    required:
                    - id
                    - type
                    - attributes
                required:
                - data
              example:
                data:
                  id: '83'
                  type: user
                  attributes:
                    provider: google
                    uid: 8c1db078-aeed-43a3-9a24-e5e4a1b4189f
                    name: test user
                    email: user_2@example.com
                    nickname: changed_name
