---
openapi: 3.2.0
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/user/sangakus":
    get:
      summary: index
      tags:
      - Api::V1::User::Sangaku
      responses:
        '200':
          description: returns only code sangakus
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
                            description:
                              type: string
                            source:
                              type: string
                            difficulty:
                              type: string
                            inputs:
                              type: array
                              items: {}
                            author_name:
                              type: string
                            shrine_name:
                              type:
                              - string
                              - 'null'
                            kind:
                              type: string
                          required:
                          - title
                          - description
                          - difficulty
                          - source
                          - inputs
                          - author_name
                        relationships:
                          type: object
                          properties:
                            user:
                              type: object
                              properties:
                                data:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                              required:
                              - data
                            shrine:
                              type: object
                              properties:
                                data:
                                  type:
                                  - object
                                  - 'null'
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                              required:
                              - data
                          required:
                          - user
                          - shrine
                      required:
                      - id
                      - type
                      - attributes
                      - relationships
                required:
                - data
              example:
                data:
                - id: '17507'
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    difficulty: easy
                    kind: code
                    source: puts 'Hello world'
                    inputs: []
                    author_name: test nickname
                    shrine_name: test_shrine
                  relationships:
                    user:
                      data:
                        id: '33171'
                        type: user
                    shrine:
                      data:
                        id: '6834'
                        type: shrine
      parameters:
      - name: kind
        in: query
        required: false
        schema:
          type: string
        example: code
      - name: shrine_id
        in: query
        required: false
        schema:
          oneOf:
          - type: string
          - type: integer
        example: any
      - name: title
        in: query
        required: false
        schema:
          type: string
        example: another
  "/api/v1/user/sangakus/{id}":
    delete:
      summary: destroy
      tags:
      - Api::V1::User::Sangaku
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 17535
      responses:
        '200':
          description: return sangaku in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          description:
                            type: string
                          source:
                            type: string
                          difficulty:
                            type: string
                          inputs:
                            type: array
                            items: {}
                          author_name:
                            type: string
                          shrine_name:
                            type: 'null'
                          kind:
                            type: string
                          code_blocks:
                            type: array
                            items: {}
                        required:
                        - title
                        - description
                        - difficulty
                        - source
                        - inputs
                        - author_name
                      relationships:
                        type: object
                        properties:
                          user:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                - id
                                - type
                            required:
                            - data
                          shrine:
                            type: object
                            properties:
                              data:
                                type: 'null'
                            required:
                            - data
                        required:
                        - user
                        - shrine
                    required:
                    - id
                    - type
                    - attributes
                    - relationships
                required:
                - data
              example:
                data:
                  id: '17535'
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    source: puts 'Hello world'
                    difficulty: easy
                    inputs: []
                    author_name: test nickname
                    shrine_name:
                    kind: code
                    code_blocks: []
                  relationships:
                    user:
                      data:
                        id: '33192'
                        type: user
                    shrine:
                      data:
    get:
      summary: show
      tags:
      - Api::V1::User::Sangaku
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 17527
      responses:
        '200':
          description: return sangaku in json formata
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          description:
                            type: string
                          source:
                            type: string
                          difficulty:
                            type: string
                          inputs:
                            type: array
                            items: {}
                          author_name:
                            type: string
                          shrine_name:
                            type: 'null'
                          kind:
                            type: string
                          code_blocks:
                            type: array
                            items: {}
                        required:
                        - title
                        - description
                        - difficulty
                        - source
                        - inputs
                        - author_name
                      relationships:
                        type: object
                        properties:
                          user:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                - id
                                - type
                            required:
                            - data
                          shrine:
                            type: object
                            properties:
                              data:
                                type: 'null'
                            required:
                            - data
                        required:
                        - user
                        - shrine
                    required:
                    - id
                    - type
                    - attributes
                    - relationships
                required:
                - data
              example:
                data:
                  id: '17527'
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    source: puts 'Hello world'
                    difficulty: easy
                    inputs: []
                    author_name: test nickname
                    shrine_name:
                    kind: code
                    code_blocks: []
                  relationships:
                    user:
                      data:
                        id: '33183'
                        type: user
                    shrine:
                      data:
