---
openapi: 3.0.3
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/user/saved_sangakus":
    get:
      summary: index
      tags:
        - Api::V1::SangakuSave
      responses:
        "200":
          description: return unsolved saved sangakus in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
                            description:
                              type: string
                            source:
                              type: string
                            difficulty:
                              type: string
                            inputs:
                              type: array
                              items: {}
                            author_name:
                              type: string
                          required:
                            - title
                            - description
                            - source
                            - difficulty
                            - inputs
                            - author_name
                        relationships:
                          type: object
                          properties:
                            user:
                              type: object
                              properties:
                                data:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                    - id
                                    - type
                              required:
                                - data
                            shrine:
                              type: object
                              properties:
                                data:
                                  nullable: true
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                    - id
                                    - type
                              required:
                                - data
                          required:
                            - user
                            - shrine
                      required:
                        - id
                        - type
                        - attributes
                        - relationships
                required:
                  - data
              example:
                data:
                  - id: "397"
                    type: sangaku
                    attributes:
                      title: test_title
                      description: test_description
                      source: puts 'Hello world'
                      difficulty: easy
                      inputs: []
                      author_name: author
                    relationships:
                      user:
                        data:
                          id: "636"
                          type: user
                      shrine:
                        data:
                          id: "246"
                          type: shrine
      parameters:
        - name: type
          in: query
          required: false
          schema:
            type: string
          example: before_answer
  "/api/v1/user/saved_sangakus/{id}":
    get:
      summary: show
      tags:
        - Api::V1::SangakuSave
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 399
        - name: type
          in: query
          required: false
          schema:
            type: string
          example: before_answer
      responses:
        "200":
          description: return sangaku in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          description:
                            type: string
                          source:
                            type: string
                          difficulty:
                            type: string
                          inputs:
                            type: array
                            items: {}
                          author_name:
                            type: string
                        required:
                          - title
                          - description
                          - source
                          - difficulty
                          - inputs
                          - author_name
                      relationships:
                        type: object
                        properties:
                          user:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                  - id
                                  - type
                            required:
                              - data
                          shrine:
                            type: object
                            properties:
                              data:
                                nullable: true
                            required:
                              - data
                        required:
                          - user
                          - shrine
                    required:
                      - id
                      - type
                      - attributes
                      - relationships
                required:
                  - data
              example:
                data:
                  id: "399"
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    source: puts 'Hello world'
                    difficulty: easy
                    inputs: []
                    author_name: author
                  relationships:
                    user:
                      data:
                        id: "638"
                        type: user
                    shrine:
                      data:
  "/api/v1/user/saved_sangakus/{id}/answer":
    get:
      summary: answer
      tags:
        - Api::V1::SangakuSave
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 400
      responses:
        "200":
          description: return answer in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          source:
                            type: string
                          status:
                            type: string
                        required:
                          - source
                          - status
                      relationships:
                        type: object
                        properties:
                          user_sangaku_save:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                  - id
                                  - type
                            required:
                              - data
                          answer_results:
                            type: object
                            properties:
                              data:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                    - id
                                    - type
                            required:
                              - data
                        required:
                          - user_sangaku_save
                          - answer_results
                    required:
                      - id
                      - type
                      - attributes
                      - relationships
                required:
                  - data
              example:
                data:
                  id: "77"
                  type: answer
                  attributes:
                    source: puts 'Hello world'
                    status: correct
                  relationships:
                    user_sangaku_save:
                      data:
                        id: "158"
                        type: user_sangaku_save
                    answer_results:
                      data:
                        - id: "77"
                          type: answer_result
