---
openapi: 3.0.3
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/user/saved_sangakus":
    get:
      summary: index
      tags:
      - Api::V1::SangakuSave
      responses:
        '200':
          description: return unsolved saved sangakus in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
                            description:
                              type: string
                            source:
                              type: string
                            difficulty:
                              type: string
                            inputs:
                              type: array
                              items: {}
                            author_name:
                              type: string
                          required:
                          - title
                          - description
                          - source
                          - difficulty
                          - inputs
                          - author_name
                        relationships:
                          type: object
                          properties:
                            user:
                              type: object
                              properties:
                                data:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                              required:
                              - data
                            shrine:
                              type: object
                              properties:
                                data:
                                  nullable: true
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                              required:
                              - data
                          required:
                          - user
                          - shrine
                      required:
                      - id
                      - type
                      - attributes
                      - relationships
                required:
                - data
              example:
                data:
                - id: '148'
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    source: puts 'Hello world'
                    difficulty: easy
                    inputs: []
                    author_name: author
                  relationships:
                    user:
                      data:
                        id: '239'
                        type: user
                    shrine:
                      data:
                        id: '94'
                        type: shrine
      parameters:
      - name: type
        in: query
        required: false
        schema:
          type: string
        example: before_answer
  "/api/v1/user/saved_sangakus/{id}":
    get:
      summary: show
      tags:
      - Api::V1::SangakuSave
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 150
      responses:
        '200':
          description: return sangaku in json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          description:
                            type: string
                          source:
                            type: string
                          difficulty:
                            type: string
                          inputs:
                            type: array
                            items: {}
                          author_name:
                            type: string
                        required:
                        - title
                        - description
                        - source
                        - difficulty
                        - inputs
                        - author_name
                      relationships:
                        type: object
                        properties:
                          user:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                - id
                                - type
                            required:
                            - data
                          shrine:
                            type: object
                            properties:
                              data:
                                nullable: true
                            required:
                            - data
                        required:
                        - user
                        - shrine
                    required:
                    - id
                    - type
                    - attributes
                    - relationships
                required:
                - data
              example:
                data:
                  id: '150'
                  type: sangaku
                  attributes:
                    title: test_title
                    description: test_description
                    source: puts 'Hello world'
                    difficulty: easy
                    inputs: []
                    author_name: author
                  relationships:
                    user:
                      data:
                        id: '241'
                        type: user
                    shrine:
                      data:
