---
openapi: 3.2.0
info:
  title: Algo Sangaku Documentation
  version: 1.0.0
servers: []
paths:
  "/api/v1/user/saved_sangakus/{saved_sangaku_id}/answer":
    get:
      summary: show
      tags:
      - Api::V1::User::SavedSangakusAnswer
      parameters:
      - name: saved_sangaku_id
        in: path
        required: true
        schema:
          type: integer
        example: 17566
      responses:
        '200':
          description: returns the status without a source and with no answer_results
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          source:
                            type:
                            - string
                            - 'null'
                          status:
                            type: string
                          kind:
                            type: string
                        required:
                        - source
                        - status
                      relationships:
                        type: object
                        properties:
                          user_sangaku_save:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                - id
                                - type
                            required:
                            - data
                          answer_results:
                            type: object
                            properties:
                              data:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                            required:
                            - data
                        required:
                        - user_sangaku_save
                        - answer_results
                    required:
                    - id
                    - type
                    - attributes
                    - relationships
                required:
                - data
              example:
                data:
                  id: '5284'
                  type: answer
                  attributes:
                    source:
                    status: correct
                    kind: reorder
                  relationships:
                    user_sangaku_save:
                      data:
                        id: '8118'
                        type: user_sangaku_save
                    answer_results:
                      data: []
    post:
      summary: create
      tags:
      - Api::V1::User::SavedSangakusAnswer
      parameters:
      - name: saved_sangaku_id
        in: path
        required: true
        schema:
          type: integer
        example: 17548
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: object
                  properties:
                    source:
                      type: string
                    block_ids:
                      type: array
                      items:
                        type: integer
              required:
              - answer
            example:
              answer:
                source: puts 'Hello wourld'
                block_ids:
                - 14138
                - 1014139
      responses:
        '200':
          description: returns 200 with an incorrect status and still saves the answer
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          source:
                            type:
                            - string
                            - 'null'
                          status:
                            type: string
                          kind:
                            type: string
                        required:
                        - source
                        - status
                      relationships:
                        type: object
                        properties:
                          user_sangaku_save:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                required:
                                - id
                                - type
                            required:
                            - data
                          answer_results:
                            type: object
                            properties:
                              data:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                                  required:
                                  - id
                                  - type
                            required:
                            - data
                        required:
                        - user_sangaku_save
                        - answer_results
                    required:
                    - id
                    - type
                    - attributes
                    - relationships
                required:
                - data
              example:
                data:
                  id: '5276'
                  type: answer
                  attributes:
                    source:
                    status: incorrect
                    kind: reorder
                  relationships:
                    user_sangaku_save:
                      data:
                        id: '8101'
                        type: user_sangaku_save
                    answer_results:
                      data: []
